# SPDX-License-Identifier: GPL-2.0-only

dtb-$(TARGET_ARM32) += \

dtb-$(TARGET_ARM64) += \
	stm32mp257f-ev1-ca35tdcid-ostl.dtb \
	stm32mp257f-ev1-revB-ca35tdcid-ostl.dtb \
	stm32mp257f-ev1-ca35tdcid-ostl-m33-examples.dtb \
	stm32mp257f-ev1-revB-ca35tdcid-ostl-m33-examples.dtb